### ISSUE TITLE
.coveragerc

### ISSUE THREAD

**Issue by willrogers** [willrogers/pml#39]
@razvanvasile do we need `.coveragerc`?  It refers to `pml` so I expect we don't.

**Comment by razvanvasile** [comment]
I changed the reference to pytac. I think that this file was used for the coverage so I assume that we need it.

**Comment by willrogers** [comment]
Why do you assume we need it?  Everything seemed to work before changing the reference.

**Comment by razvanvasile** [comment]
You are right. I will remove it and if we notice that something broke we could add it back in.

**Comment by willrogers** [comment]
I agree!
